
server:
  port: 8080

spring:
  application:
    name: embedded-iam
  banner:
    location: classpath:banner.txt
  jpa:
    defer-datasource-initialization: true
  datasource:
    username: sa
    url: jdbc:h2:mem:sinadb;DB_CLOSE_ON_EXIT=FALSE

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin
    realmImportFile: blubank-realm.json